import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "the Move",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div>
          <h1>The Move</h1>
          <h2>General</h2>
          <nav>
            <div>
              <Link href="/">Dashboard</Link>
              <Link href="/checklist">Checklist</Link>
              <Link href="/plan">Plan</Link>
              <Link href="/savings">Savings</Link>
            </div>
            <Link href="/settings">Settings</Link>
          </nav>
        </div>

        {children}
      </body>
    </html>
  );
}
